name: Atualizar IPs AnyDesk

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas
  workflow_dispatch:        # Permite execução manual

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar ferramentas DNS
        run: sudo apt-get install -y dnsutils

      - name: Gerar lista de IPs
        run: |
          dig +short relays.net.anydesk.com > anydesk_ips.txt
          sort -u anydesk_ips.txt -o anydesk_ips.txt

      - name: Commit e Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # Atualiza a URL remota para usar autenticação via token
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

          # Adiciona e faz commit se houver alterações
          git add anydesk_ips.txt

          if git diff --cached --quiet; then
            echo "Nenhuma mudança no arquivo. Nada para comitar."
          else
            git commit -m "Atualização automática dos IPs do AnyDesk"
            git push origin HEAD
          fi
