name: Atualizar IPs AWS

on:
  schedule:
    - cron: '0 3 * * *'  # Executa todo dia às 3h da manhã
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar script
        run: python aws_ip_filter.py

      - name: Verificar arquivo gerado
        run: |
          ls -l aws_ips.txt
          cat aws_ips.txt

      - name: Commit e push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add aws_ips.txt
          git commit -m "Atualiza IPs AWS"
          git push
