name: Atualizar IPs AnyDesk

on:
  schedule:
    - cron: '0 4 * * *'  # Executa diariamente às 1h da manhã no Brasil (UTC−3)
  workflow_dispatch:      # Permite execução manual

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar ferramentas DNS
        run: sudo apt-get install -y dnsutils

      - name: Gerar lista de IPs
        run: |
          mkdir -p providers
          dig +short relays.net.anydesk.com > providers/anydesk_ips.txt
          sort -u providers/anydesk_ips.txt -o providers/anydesk_ips.txt

      - name: Commit e Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # Atualiza a URL remota para usar autenticação via token
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

          # Adiciona e faz commit se houver alterações
          git add providers/anydesk_ips.txt

          if git diff --cached --quiet; then
            echo "Nenhuma mudança no arquivo. Nada para comitar."
          else
            git commit -m "Atualização automática dos IPs do AnyDesk"
            git push origin HEAD
          fi
